---
- name: "configuration play."
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - node_version: 13.8.0

  pre_tasks:
    - name: "wait 600 seconds for ec2 instance to become reachable/usable."
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 30
        timeout: 1200
        state: started

    - name: "install python"
      apt:
        name: python3
        state: present

  roles:
    - configure-server
