---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: Install nvm
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Install custom Node.js version
  script: |
    source ~/.bashrc
    nvm install 13.8

- name: "install NPM"
  apt:
    name: npm
    state: present

- name: "install pm2"
  npm:
    name: pm2
    global: yes
