---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "add nodejs 13"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_13.x | bash -
    apt-get install -y nodejs

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
