---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: Install Node.js
  ansible.builtin.package:
    name: nodejs
    state: present
    version: "{{ node_version }}"
    update_cache: yes

- name: "install NPM"
  apt:
    name: npm
    state: present

- name: "install pm2"
  npm:
    name: pm2
    global: yes
