- name: "create app directory"
  file:
    path: ~/app
    state: directory

- name: Copy artifact to server
  copy:
    src: "artifact.tar.gz"
    dest: "~/app/artifact.tar.gz"

- name: Extract the zipped artifact
  unarchive:
    src: "~/app/artifact.tar.gz"
    dest: "~/app"
    remote_src: yes

- name: Start the app
  shell: |
    cd ~/app
    pm2 start npm -- start
