- name: Copy artifact to server
  copy:
    src: "artifact.tar.gz"
    dest: "~/tmp/artifact.tar.gz"

- name: Extract the zipped artifact
  unarchive:
    src: "~/tmp/artifact.tar.gz"
    dest: "~/app"

- name: Install dependencies
  npm:
    path: "~/app"
    command: install

- name: Stop the app
  command: "pm2 stop default"

- name: Start the app
  command: "pm2 start npm -- start"
