- name: "create app directory"
  file:
    path: ~/app
    state: directory

- name: Copy artifact to server
  copy:
    src: "artifact.tar.gz"
    dest: "~/app/artifact.tar.gz"

# - name: Extract the zipped artifact
#   unarchive:
#     src: "tmp/artifact.tar.gz"
#     dest: "~/app"

# - name: Stop the app
#   command: "pm2 stop default"

- name: Start the app
  command: "pm2 start ~/app/npm -- start"
